Revert "Small changes to French translation (Petites modifications mineures)"
This reverts commit 4432e982616cd871cf1ae5c5706da09e98077433.

Exception: "Nom / Mot de Passe" --> "Nom / Mot de passe"